server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Activar SSI para inyectar la IP del cliente del docker
    ssi on;
    ssi_types text/html;

    # Gzip compresión para mayor velocidad
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Manejar rutas de Single Page Application (SPA)
    location / {
        try_files $uri $uri/ /index.html;
        # Evitar caché en el index para que la IP inyectada sea siempre la del cliente actual
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # Caché estática para assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
